### ISSUE TITLE
[documentation] Exact installation commads for 3 distros.

### ISSUE THREAD

**Issue by ezbik** [moonbaseDelta/OSfooler-ng#5]
# Distro specific steps.

Choose one from those below.

## Centos 7

```
yum install epel-release
yum install python git python-pip wget gcc make python-devel libnetfilter_queue-devel libnfnetlink-devel 
```

## Centos 8

```
sed -i s/enabled=0/enabled=1/ /etc/yum.repos.d/CentOS-PowerTools.repo 
yum install epel-release
yum install python2 git python2-pip wget gcc make python2-devel libnetfilter_queue-devel libnfnetlink-devel
```

## Ubuntu 18.04

```
apt install libnetfilter-queue-dev libnfnetlink-dev python python-setuptools python-pip
```

# Install OSfooler-ng

After distro specific steps are done.

```
pip2 install NetfilterQueue
git clone https://github.com/moonbaseDelta/OSfooler-ng ; cd OSfooler-ng
python2 setup.py install
osfooler-ng -u 
osfooler-ng -o Windows  -d "SP3" -i tun0 
```

## Check

After Osfooler-ng is installed & has been launched.

```
curl http://witch.valdikss.org.ru/ -Ss | sed -n '/^<pre/,/NTL/p'
```

Should return  `Detected OS   = Windows NT kernel [generic]`

## Notes

- some home routers do change TCP options, so consider using a VPN to the cloud for tests
- Virtualbox also may change TCP options, so GuestVM->Host->VPN may not work because TCP opts are changed between GuestVM->Host.

**Comment by moonbaseDelta** [comment]
Added to the wiki https://github.com/moonbaseDelta/OSfooler-ng/wiki/Installation

**Comment by ezbik** [comment]
Thanks @moonbaseDelta , what about Checks & Notes sections? I consider them important too.

**Comment by moonbaseDelta** [comment]
My bad, just fixed it.
